config/routes.rb
Rails.application.routes.draw do
  resources :handles
  get 'pages/index'
  get 'pages/about'

  devise_for :users

  root 'pages#index'

end

app/models/handle.rb
class Handle < ActiveRecord::Base
  has_and_belongs_to_many :users, :uniq => true
  validates :username, presence: true, length: {maximum: 25}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :handles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/codechef_ids_controller.rb
class CodechefIdsController < ApplicationController
  before_action :set_codechef_id, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /codechef_ids
  # GET /codechef_ids.json
  def index
    @codechef_ids = current_user.codechef_ids
  end

  # GET /codechef_ids/1
  # GET /codechef_ids/1.json
  def show
  end

  # GET /codechef_ids/new
  def new
    @codechef_id = CodechefId.new
  end

  # GET /codechef_ids/1/edit
  def edit
  end

  # POST /codechef_ids
  # POST /codechef_ids.json
  def create
    @codechef_id = CodechefId.new(codechef_id_params)
    @codechef_id.user = current_user

    url = "https://www.codechef.com/users/#{@codechef_id.username}"
    status = 1
    until status == 200 do
      begin
        r = HTTParty.get(url,:verify => false,timeout: 5,follow_redirects: false )
        puts r.code
      if r.code == 200
        status = 200
      elsif r.code == 302
        redirect_to new_codechef_id_path , notice: "#{@codechef_id.username} is not a valid codechef id"
        return
      end
      rescue HTTParty::Error,Net::OpenTimeout, Net::ReadTimeout
        puts "Error"
      end
    end
    response = Nokogiri::HTML(r.body)
    response = response.css('.profile a')
    userSolvedProblems = []
    response.each do | link |
      link["href"] = "https://www.codechef.com#{link["href"]}"
      userSolvedProblems.push(link.to_s)
    end
    @codechef_id.solved_problems = userSolvedProblems.join(';')

    respond_to do |format|
      if @codechef_id.save
        format.html { redirect_to @codechef_id, notice: "#{@codechef_id.username} was successfully added." }
        format.json { render :show, status: :created, location: @codechef_id }
      else
        format.html { render :new }
        format.json { render json: @codechef_id.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codechef_ids/1
  # PATCH/PUT /codechef_ids/1.json
  def update
    respond_to do |format|
      if @codechef_id.update(codechef_id_params)
        format.html { redirect_to @codechef_id, notice: "#{@codechef_id.username} was successfully updated." }
        format.json { render :show, status: :ok, location: @codechef_id }
      else
        format.html { render :edit }
        format.json { render json: @codechef_id.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codechef_ids/1
  # DELETE /codechef_ids/1.json
  def destroy
    @codechef_id.destroy
    respond_to do |format|
      format.html { redirect_to codechef_ids_url, notice: "#{@codechef_id.username} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_codechef_id
      @codechef_id = current_user.codechef_ids.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def codechef_id_params
      params.require(:codechef_id).permit(:username)
    end
end

app/controllers/handles_controller.rb
class HandlesController < ApplicationController
  before_action :set_handle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /codechef_ids
  # GET /codechef_ids.json
  def index
    @codechef_ids = current_user.handles
  end

  # GET /codechef_ids/1
  # GET /codechef_ids/1.json
  def show
  end

  # GET /codechef_ids/new
  def new
    @codechef_id = Handle.new
  end

  # GET /codechef_ids/1/edit
  def edit
  end

  # POST /codechef_ids
  # POST /codechef_ids.json
  def create
    @codechef_id = Handle.find_by_username(params[:handle][:username])
    if @codechef_id
       
      if @codechef_id.users.exists?(current_user)
        redirect_to root_path, notice: "You have already added #{@codechef_id.username} for tracking"
      else
      @codechef_id.users<<current_user
      @codechef_id.save!
      redirect_to @codechef_id, notice: "#{@codechef_id.username} was successfully added."
      end
    else
    @codechef_id = Handle.new(handle_params)
    @codechef_id.users<<current_user
    if @codechef_id[:team] == true
      url = "https://www.codechef.com/teams/view/#{@codechef_id.username}"
    else
      url = "https://www.codechef.com/users/#{@codechef_id.username}"
    end
    status = 1
    until status == 200 do
      begin
        r = HTTParty.get(url,:verify => false,timeout: 5,follow_redirects: false )
        puts r.code
      if r.code == 200
        status = 200
      elsif r.code == 302
        redirect_to new_handle_path , notice: "#{@codechef_id.username} is not a valid codechef id"
        return
      end
      rescue HTTParty::Error,Net::OpenTimeout, Net::ReadTimeout
        puts "Error"
      end
    end
    response = Nokogiri::HTML(r.body)
    response = response.css('article p a')
    userSolvedProblems = []
    response.each do | link |
      link["href"] = "https://www.codechef.com#{link["href"]}"
      if link["href"].include?("users") && @codechef_id.team == true
        ;
      else
      userSolvedProblems.push(link.to_s)
      end
    end
    @codechef_id.solved_problems = userSolvedProblems.join(';')

    respond_to do |format|
      if @codechef_id.save
        format.html { redirect_to @codechef_id, notice: "#{@codechef_id.username} was successfully added." }
        format.json { render :show, status: :created, location: @codechef_id }
      else
        format.html { render :new }
        format.json { render json: @codechef_id.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # PATCH/PUT /codechef_ids/1
  # PATCH/PUT /codechef_ids/1.json
  def update
    respond_to do |format|
      if @codechef_id.update(handle_params)
        format.html { redirect_to @codechef_id, notice: "#{@codechef_id.username} was successfully updated." }
        format.json { render :show, status: :ok, location: @codechef_id }
      else
        format.html { render :edit }
        format.json { render json: @codechef_id.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codechef_ids/1
  # DELETE /codechef_ids/1.json
  def destroy
    user_to_be_removed_from_association = @codechef_id.users.find(current_user.id)
    if user_to_be_removed_from_association
      @codechef_id.users.delete(user_to_be_removed_from_association)
      if @codechef_id.users.blank?
        @codechef_id.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_to handles_url, notice: "#{@codechef_id.username} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handle
      @codechef_id = current_user.handles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handle_params
      params.require(:handle).permit(:username,:team)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@codechef_ids = Handle.order("created_at DESC").limit(2)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codechef_ids_helper.rb
module CodechefIdsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/codechef_ids/edit.html.erb
<h1>Editing Codechef</h1>

<%= render 'form' %>

<%= link_to 'Show', @codechef_id %> |
<%= link_to 'Back', codechef_ids_path %>

app/views/codechef_ids/index.html.erb
<h3>Listing Codechef Ids</h3>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @codechef_ids.each do |codechef_id| %>
      <tr>
        <td><%= codechef_id.username %></td>
        <td><%= link_to 'Show', codechef_id %></td>
        <td><%= link_to 'Destroy', codechef_id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Codechef Id', new_codechef_id_path %>

app/views/codechef_ids/new.html.erb
<h3>New Codechef Id to stalk!</h3>
<p>Adding new id might take some time.</p>
<%= render 'form' %>

<%= link_to 'Back', codechef_ids_path %>

app/views/codechef_ids/show.html.erb
  <h3 class="center"><%= @codechef_id.username %></h3>

<ul class="collection with-header">
<li class="collection-header"><h4>Solved Problems</h4>(other links in profile might be included at top)</li>
<% @codechef_id.solved_problems.split(';').each do |link| %>
<li class="collection-item"><%= raw link %></li>
<% end %>
</ul>
<br>
<%= link_to 'Back', codechef_ids_path %>
      

app/views/handles/_form.html.erb
<%= form_for(@codechef_id) do |f| %>
  <% if @codechef_id.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@codechef_id.errors.count, "error") %> prohibited this codechef_id from being saved:</h4>

      <ul>
      <% @codechef_id.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username,required: true %>
  </div>
  <p>Adding Team?</p>
    <div class="switch">
      <label>
        No
      <%= f.check_box :team %>
      <span class="lever"></span>
        Yes (Add team handle and not team name. Team handle is shown on team profile page.)
      </label>
    </div>
    <br>
  
  <div class="actions">
    <button class="btn waves-effect waves-light" type="submit" name="action">Start Stalking!
            <i class="material-icons right">send</i>
  </div>
  <br>
<% end %>

app/views/handles/edit.html.erb
<h1>Editing Codechef</h1>

<%= render 'form' %>

<%= link_to 'Show', @codechef_id %> |
<%= link_to 'Back', handles_path %>

app/views/handles/index.html.erb
<h3>Listing Codechef Ids</h3>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Team</th>
      <th colspan="3"></th>   
    </tr>
  </thead>

  <tbody>
    <% @codechef_ids.each do |codechef_id| %>
      <tr>
        <td><%= codechef_id.username %></td>
        <td><%= codechef_id.team %></td>
        <td><%= link_to 'Show', codechef_id %></td>
        <td><%= link_to 'Destroy', codechef_id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Codechef Id', new_handle_path %>

app/views/handles/new.html.erb
<br>
<br>
<div class="row">
<div class="card col m8 offset-m2 s12">
<h3>New Codechef Id to stalk!</h3>
<%= render 'form' %>

<%= link_to 'Back', handles_path %>
<br>
<br>
</div>
</div>

app/views/handles/show.html.erb
  <h3 class="center"><%= @codechef_id.username %></h3>

<ul class="collection with-header">
<li class="collection-header"><h4>Solved Problems</h4>(other links in profile might be included at top)</li>
<% @codechef_id.solved_problems.split(';').each do |link| %>
<li class="collection-item"><%= raw link %></li>
<% end %>
</ul>
<br>
<%= link_to 'Back', handles_path %>
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if content_for?(:title) %>
      <%= yield :title %>
  <% else %>
  <title>Home | CodeStalk</title>
  <% end %>
  <meta charset="utf-8">
  <meta name="robots" content="noodp">
    <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="theme-color" content="#e57373 ">

  <meta name="revisit-after" content="7 days">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Font-Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>

  <!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <% if content_for?(:meta_og) %>
      <%= yield :meta_og %>
  <% else %>
      <meta property="og:title" content="Home | CodeStalk"/>
      <meta property="og:type" content="website"/>
      <meta property="og:url" content="https://codestalk.herokuapp.com/"/>
      <meta property="og:image" content="<%=image_url("codestalk.PNG")%>"/>
  <% end %>
</head>
<body>
  <header>
<nav>
    <div class="nav-wrapper" >
      <a href="<%= root_path %>" class="brand-logo center">CodeStalk</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if !user_signed_in? %>
        <li><%= link_to 'Login',new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
        <li><%= link_to 'Logout',destroy_user_session_path,:method => :delete %></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo" >
        <% if !user_signed_in? %>
        <li><%= link_to 'Login',new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
        <li><%= link_to 'Logout',destroy_user_session_path,:method => :delete %></li>
        <% end %>
      </ul>
    </div>    
</nav>
</header>
<main>
<div class="container">
<%= yield %>
</div>
</main>
<footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">CodeStalk</h5>
          <div class="share-buttons">
          <a href="https://www.facebook.com/inventionsbyhamid.java.h9k6"><i class="fa fa-facebook fa-lg"></i></a>
          <a href="https://twitter.com/hamidInventions"><i class="fa fa-twitter fa-lg"></i></a>
          <a href="https://www.linkedin.com/in/hamidsiddiquilinkedin"><i class="fa fa-linkedin fa-lg"></i></a>
          <a href="https://github.com/inventionsbyhamid"><i class="fa fa-github fa-lg"></i></a>
          <a href="https://www.instagram.com/inventionsbyhamid"><i class="fa fa-instagram fa-lg"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        Made with <i class="fa fa-heart"></i> by <a class="lime-text text-accent-2" href="https://twitter.com/hamidInventions">Hamid</a>
        <%= link_to 'About',pages_about_path,:class=>"grey-text text-lighten-4 right" %>
      </div>
    </div>
  </footer>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <% unless flash.empty? %>
  <script>
  <% if flash.notice %>
  Materialize.toast('<%=flash.notice%>',5000);
  <% else %>
  Materialize.toast('<%=flash.alert%>',5000);
  <% end %>
  </script>
  <% end %>
</html>

app/views/pages/about.html.erb
<br>
<br>
<div class ="row">
    <div class="card col m8 offset-m2 s12 z-depth-2 red waves-effect waves-light">
            <div class="filter red" style="opacity: 0.7;">
                <div class="red-text text-darken-4 center">
                    <span style="font-size: 50px;">&lt; About /&gt;</span>
                </div>
            </div>
        <div class="card-content white-text flow-text">
            <div class="card-title">
                <h4>About</h4>
            </div>
            CodeStalk is a weekend project, initial thoughts were made by my friend Shivam.
            <br>
            <br>Competitive Programming makes you competitive :P and I often visit my batchmates profile to see how many problems they have solved. To automate that process CodeStalk was built.
            <br>
            <br>CodeStalk sends email updates to let you know about recent successful submissions from users in your track list!
            <br>
            <a href="https://github.com/inventionsbyhamid/codestalk">Code on Github</a>
        </div>
    </div>
</div>
    

app/views/pages/index.html.erb
<% if !user_signed_in? %>
<div class="row">
<div class="col l6 offset-l3 m12 s12 center">
<h3>Stalk your friends!</h3>
<h5>Get email updates when someone solves a problem on codechef.com!</h5>
<br>
<h4><%= link_to 'Start Stalking',new_handle_path %></h4>
</div>
</div>
<div class="col l6 offset-l3 m12 s12 center">
<% @codechef_ids.each do |recent_id| %>
<p><%= "Someone added #{recent_id.username} for tracking #{time_ago_in_words(recent_id.created_at)} ago"%></p>
<% end %>
</div>
<% else %>
<br>
<br>
<div class="row">
<div class="card col l10 offset-l1 m12 s12">
<h3>Listing Codechef Ids</h3>
<h5><%= link_to 'New Codechef Id', new_handle_path %></h5>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.handles.each do |codechef_id| %>
      <tr>
        <td><%= codechef_id.username %></td>
        <td><%= codechef_id.team %></td>
        <td><%= link_to 'Show', codechef_id %></td>
        <td><%= link_to 'Destroy', codechef_id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>
</div>
<% end %>